"""
Shared utilities and authentication helper functions for the Mosquitto
Streamlit admin GUI. This module centralizes configuration paths,
password hashing, admin credential management, user management,
certificate generation, configuration file handling, and broker
reload logic. Each Streamlit page imports this module to gain
access to common functionality and a `require_login` function
that enforces file-based admin authentication.

The admin credentials are stored in `/config/admin_pwfile` in
Mosquitto's `$7$` PBKDF2-SHA512 format. The first time you run
the GUI, `require_login()` will prompt you to set an admin
username and password. Thereafter, pages will display a login
form until you authenticate.
"""

import os
import base64
import hashlib
import hmac
import re
import subprocess
import signal
from dataclasses import dataclass
from datetime import datetime, timedelta
from ipaddress import ip_address
from typing import Callable, List, Tuple, Optional, Dict, Any

import streamlit as st
from cryptography import x509
from cryptography.x509.oid import NameOID, ExtendedKeyUsageOID
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa

# -----------------------------------------------------------------------------
# Paths and constants

# Path to the admin password file used to secure the admin GUI.
ADMIN_CONFIG_DIR = os.environ.get("ADMIN_CONFIG_DIR", "/admin-gui/config")
ADMIN_PWFILE = os.path.join(ADMIN_CONFIG_DIR, "admin_pwfile")

# Directory for trigger-file signaling between admin and mosquitto
SIGNALS_DIR = os.environ.get("SIGNALS_DIR", "/signals")

# Base directory for Mosquitto configuration. This is injected via env.
MOSQUITTO_CONFIG_DIR = os.environ.get("MOSQUITTO_CONFIG_DIR", "/config")

# Path to the password file used by Mosquitto for MQTT user authentication.
PWFILE = os.path.join(MOSQUITTO_CONFIG_DIR, "pwfile")

# Directory that can hold additional password files for per-listener auth.
PASSWD_FILES_DIR = os.path.join(MOSQUITTO_CONFIG_DIR, "passwd_files")

# Paths to TLS and configuration artifacts.
ACLFILE = os.path.join(MOSQUITTO_CONFIG_DIR, "aclfile")
CAFILE = os.path.join(MOSQUITTO_CONFIG_DIR, "ca-root-cert.crt")      # server CA
CERTFILE = os.path.join(MOSQUITTO_CONFIG_DIR, "server.crt")          # server cert
KEYFILE = os.path.join(MOSQUITTO_CONFIG_DIR, "server.key")           # server key
CLIENT_CAFILE = os.path.join(MOSQUITTO_CONFIG_DIR, "client-ca.crt")  # client CA
MOSQCONF = os.path.join(MOSQUITTO_CONFIG_DIR, "mosquitto.conf")      # broker config

# Default mosquitto.conf content used when the file does not exist.
DEFAULT_CONF = """\
# Default Mosquitto configuration generated by the admin GUI.
# Adjust as needed and reload the broker to apply changes.
per_listener_settings true

# Plain MQTT (optional)
listener 1883 0.0.0.0
allow_anonymous true
#password_file /mosquitto/config/pwfile

# TLS listener
# listener 8883 0.0.0.0
# cafile /mosquitto/config/ca-root-cert.crt
# certfile /mosquitto/config/server.crt
# keyfile /mosquitto/config/server.key
# require_certificate false
# use_identity_as_username false
# password_file /mosquitto/config/pwfile

# Logging
log_dest stdout
log_type error
log_type warning
log_type notice
log_type information
"""


@dataclass
class PasswordFileEntry:
    """Metadata about a Mosquitto password file."""

    path: str
    label: str
    is_default: bool
    usernames: List[str]
    exists: bool
    size_bytes: Optional[int]
    modified: Optional[datetime]

    @property
    def user_count(self) -> int:
        return len(self.usernames)

# -----------------------------------------------------------------------------
# PBKDF2 helpers and admin credential management

def mosq_pbkdf2_sha512_hash(password: str, iterations: int = 20000, salt_bytes: int = 12) -> str:
    """Return a Mosquitto-compatible PBKDF2-SHA512 hash in $7$ format."""
    if isinstance(password, str):
        password = password.encode("utf-8")
    salt = os.urandom(salt_bytes)
    dk = hashlib.pbkdf2_hmac("sha512", password, salt, iterations)
    b64salt = base64.b64encode(salt).decode("ascii")
    b64dk = base64.b64encode(dk).decode("ascii")
    return f"$7${iterations}${b64salt}${b64dk}"


def verify_mosq_7(password: str, stored: str) -> bool:
    """Verify a plaintext password against a stored $7$ PBKDF2-SHA512 hash."""
    try:
        if not stored.startswith("$7$"):
            return False
        _, iters, b64salt, b64dk = stored.split("$")[1:5]
        iters = int(iters)
        salt = base64.b64decode(b64salt)
        want = base64.b64decode(b64dk)
        got = hashlib.pbkdf2_hmac("sha512", password.encode("utf-8"), salt, iters)
        return hmac.compare_digest(got, want)
    except Exception:
        return False


def load_admin_credentials() -> Tuple[Optional[str], Optional[Callable[[str], bool]]]:
    """Load the admin username and a password verification callable."""
    if not os.path.exists(ADMIN_PWFILE):
        return None, None
    try:
        with open(ADMIN_PWFILE, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or ":" not in line:
                    continue
                user, hashv = line.split(":", 1)
                user = user.strip()
                hashv = hashv.strip()
                if user and hashv:
                    return user, (lambda pw: verify_mosq_7(pw, hashv))
    except Exception:
        pass
    return None, None


def save_admin_credentials(username: str, password: str) -> None:
    """Persist the admin credentials to the ADMIN_PWFILE."""
    h = mosq_pbkdf2_sha512_hash(password, iterations=20000)
    os.makedirs(os.path.dirname(ADMIN_PWFILE), exist_ok=True)
    with open(ADMIN_PWFILE, "w", encoding="utf-8", newline="\n") as f:
        f.write(f"{username}:{h}\n")


def require_login() -> bool:
    """Enforce that the user is authenticated before continuing."""
    admin_user, admin_verify = load_admin_credentials()

    # Initialize session variables
    st.session_state.setdefault("auth_ok", False)
    st.session_state.setdefault("auth_user", None)

    # Bootstrap: if no admin credentials exist, prompt for them
    if admin_user is None or admin_verify is None:
        with st.container(border=True):
            st.subheader("Set Admin Credentials")
            col1, col2 = st.columns(2)
            with col1:
                username = st.text_input("Username", value="admin", key="init_username")
            with col2:
                password = st.text_input("New Password", type="password", key="init_password", help="Min 8 characters")
            if st.button("Save Admin Credentials", key="init_save", disabled=len(password) < 8):
                if not username or len(password) < 8:
                    st.error("Username required and password must be at least 8 characters.")
                else:
                    save_admin_credentials(username, password)
                    st.success("Admin credentials saved. Please log in.")
                    st.rerun()
        return False

    # Already logged in?
    if st.session_state.get("auth_ok") and st.session_state.get("auth_user") == admin_user:
        return True

    # Show login form
    with st.container(border=True):
        st.subheader("Sign in")
        u = st.text_input("Username", key="login_username")
        p = st.text_input("Password", type="password", key="login_password")
        if st.button("Sign in", key="login_submit"):
            if hmac.compare_digest(u or "", admin_user) and admin_verify(p or ""):
                st.session_state["auth_ok"] = True
                st.session_state["auth_user"] = admin_user
                st.rerun()
            else:
                st.error("Invalid username or password.")
    return False

# -----------------------------------------------------------------------------
# Session helpers

def logout_button() -> None:
    """Render a logout button and handle session cleanup."""
    if st.button("Logout"):
        st.session_state["auth_ok"] = False
        st.session_state["auth_user"] = None
        st.success("Logged out.")
        st.rerun()

# -----------------------------------------------------------------------------
# User management helpers

_PW_NAME_RE = re.compile(r"^[A-Za-z0-9_.-]+$")


def _pw_permissions(path: str) -> None:
    """Best-effort permissions adjustment for a password file."""

    try:
        subprocess.run(["chown", "1883:1883", path], check=False)
    except Exception:
        pass
    try:
        subprocess.run(["chmod", "0700", path], check=False)
    except Exception:
        pass


def read_pw_users(path: Optional[str] = None) -> List[str]:
    """Return a list of usernames defined in a Mosquitto password file."""

    target = path or PWFILE
    users: List[str] = []
    if os.path.exists(target):
        with open(target, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or ":" not in line:
                    continue
                user, _hashv = line.split(":", 1)
                users.append(user)
    return users


def upsert_user(username: str, password: str, path: Optional[str] = None) -> None:
    """Add or update a user's entry in the specified password file."""

    target = path or PWFILE
    h = mosq_pbkdf2_sha512_hash(password, iterations=20000)
    lines: List[str] = []
    if os.path.exists(target):
        with open(target, "r", encoding="utf-8") as f:
            lines = [ln for ln in f.read().splitlines() if ln.strip()]
        # Remove any existing entry for this user
        lines = [ln for ln in lines if not ln.startswith(username + ":")]
    lines.append(f"{username}:{h}")
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    if os.path.exists(target):
        _pw_permissions(target)


def delete_user(username: str, path: Optional[str] = None) -> None:
    """Remove a user from the specified password file if present."""

    target = path or PWFILE
    if not os.path.exists(target):
        return
    with open(target, "r", encoding="utf-8") as f:
        lines = [ln for ln in f.read().splitlines() if ln.strip()]
    lines = [ln for ln in lines if not ln.startswith(username + ":")]
    with open(target, "w", encoding="utf-8", newline="\n") as f:
        if lines:
            f.write("\n".join(lines) + "\n")
        else:
            f.truncate(0)
    if os.path.exists(target):
        _pw_permissions(target)


def create_password_file(name: str) -> str:
    """Create a new password file inside PASSWD_FILES_DIR and return its path."""

    cleaned = (name or "").strip()
    if not cleaned:
        raise ValueError("Password file name is required.")
    if not _PW_NAME_RE.fullmatch(cleaned):
        raise ValueError("Use only letters, numbers, dots, underscores, or dashes.")
    os.makedirs(PASSWD_FILES_DIR, exist_ok=True)
    path = os.path.join(PASSWD_FILES_DIR, cleaned)
    if os.path.exists(path):
        raise FileExistsError(f"Password file '{cleaned}' already exists.")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("")
    _pw_permissions(path)
    return path


def _build_password_file_entry(path: str, label: str, is_default: bool) -> PasswordFileEntry:
    usernames = read_pw_users(path)
    exists = os.path.exists(path)
    size_bytes: Optional[int] = None
    modified: Optional[datetime] = None
    if exists:
        try:
            size_bytes = os.path.getsize(path)
        except OSError:
            size_bytes = None
        try:
            modified = datetime.utcfromtimestamp(os.path.getmtime(path))
        except OSError:
            modified = None
    return PasswordFileEntry(
        path=path,
        label=label,
        is_default=is_default,
        usernames=usernames,
        exists=exists,
        size_bytes=size_bytes,
        modified=modified,
    )


def discover_password_files(include_default: bool = True) -> List[PasswordFileEntry]:
    """Return metadata for known Mosquitto password files."""

    entries: List[PasswordFileEntry] = []
    if include_default:
        entries.append(_build_password_file_entry(PWFILE, "pwfile (default)", True))
    if os.path.isdir(PASSWD_FILES_DIR):
        for name in sorted(os.listdir(PASSWD_FILES_DIR)):
            full = os.path.join(PASSWD_FILES_DIR, name)
            if not os.path.isfile(full):
                continue
            entries.append(_build_password_file_entry(full, f"passwd_files/{name}", False))
    return entries

# -----------------------------------------------------------------------------
# TLS certificate generation

def gen_server_ca_and_cert(cn: str, alt_hosts: List[str], days: int = 825) -> None:
    """Generate a self-signed CA and server certificate/key for TLS."""
    now = datetime.utcnow()
    # Generate CA key and certificate
    ca_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    ca_name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, u"Mosquitto Server CA")])
    ca_cert = (
        x509.CertificateBuilder()
        .subject_name(ca_name)
        .issuer_name(ca_name)
        .public_key(ca_key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now - timedelta(minutes=1))
        .not_valid_after(now + timedelta(days=3650))
        .add_extension(x509.BasicConstraints(ca=True, path_length=None), critical=True)
        .add_extension(
            x509.KeyUsage(
                digital_signature=False,
                content_commitment=False,
                key_encipherment=False,
                data_encipherment=False,
                key_agreement=False,
                key_cert_sign=True,
                crl_sign=True,
                encipher_only=False,
                decipher_only=False,
            ),
            critical=True,
        )
        .sign(private_key=ca_key, algorithm=hashes.SHA256())
    )
    # Generate server key
    server_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    # Subject for server cert
    server_name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, cn)])
    san_list = []
    for item in alt_hosts:
        item = item.strip()
        if not item:
            continue
        try:
            san_list.append(x509.IPAddress(ip_address(item)))
        except ValueError:
            san_list.append(x509.DNSName(item))
    server_cert = (
        x509.CertificateBuilder()
        .subject_name(server_name)
        .issuer_name(ca_cert.subject)
        .public_key(server_key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(now - timedelta(minutes=1))
        .not_valid_after(now + timedelta(days=days))
        .add_extension(x509.SubjectAlternativeName(san_list), critical=False)
        .add_extension(x509.ExtendedKeyUsage([ExtendedKeyUsageOID.SERVER_AUTH]), critical=False)
        .add_extension(x509.BasicConstraints(ca=False, path_length=None), critical=True)
        .add_extension(
            x509.KeyUsage(
                digital_signature=True,
                content_commitment=False,
                key_encipherment=True,
                data_encipherment=False,
                key_agreement=False,
                key_cert_sign=False,
                crl_sign=False,
                encipher_only=False,
                decipher_only=False,
            ),
            critical=True,
        )
        .sign(private_key=ca_key, algorithm=hashes.SHA256())
    )
    # Write files
    os.makedirs(os.path.dirname(CAFILE), exist_ok=True)
    with open(CAFILE, "wb") as f:
        f.write(ca_cert.public_bytes(serialization.Encoding.PEM))
    with open(KEYFILE, "wb") as f:
        f.write(
            server_key.private_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PrivateFormat.TraditionalOpenSSL,
                encryption_algorithm=serialization.NoEncryption(),
            )
        )
    with open(CERTFILE, "wb") as f:
        f.write(server_cert.public_bytes(serialization.Encoding.PEM))

# -----------------------------------------------------------------------------
# Broker reload / restart

def reload_broker() -> Tuple[bool, str]:
    """
    Reload mosquitto configuration.

    Strategy:
      1) If the Mosquitto process is visible in this namespace, send SIGHUP.
      2) Otherwise (or on failure), create a trigger file at $SIGNALS_DIR/reload
         for the mosquitto watcher to handle.
    """
    # Attempt direct SIGHUP if possible
    try:
        res = subprocess.run(["pidof", "mosquitto"], capture_output=True, text=True)
        if res.returncode == 0 and res.stdout.strip():
            pid = int(res.stdout.strip().split()[0])
            os.kill(pid, signal.SIGHUP)
            return True, "Reload requested via SIGHUP (pid namespace shared)."
    except Exception:
        pass

    # Fallback: write a reload trigger file
    try:
        os.makedirs(SIGNALS_DIR, exist_ok=True)
        tmp = os.path.join(SIGNALS_DIR, "reload.tmp")
        with open(tmp, "w", encoding="utf-8", newline="\n") as f:
            f.write("")
        os.replace(tmp, os.path.join(SIGNALS_DIR, "reload"))
        return True, f"Reload requested via trigger file in {SIGNALS_DIR}."
    except Exception as e:
        return False, f"Reload not possible: {e}"

def restart_broker() -> Tuple[bool, str]:
    """Request mosquitto to restart (graceful SIGTERM handled by in-broker watcher)."""
    try:
        os.makedirs(SIGNALS_DIR, exist_ok=True)
        tmp = os.path.join(SIGNALS_DIR, "restart.tmp")
        with open(tmp, "w", encoding="utf-8", newline="\n") as f:
            f.write("")
        os.replace(tmp, os.path.join(SIGNALS_DIR, "restart"))
        return True, f"Restart requested via trigger file in {SIGNALS_DIR}."
    except Exception as e:
        return False, f"Restart not possible: {e}"

# -----------------------------------------------------------------------------
# Config file helpers

def read_text_or(path: str, default: str = "") -> str:
    """Read a file as text or return a default string if it doesn't exist."""
    if not os.path.exists(path):
        return default
    with open(path, "r", encoding="utf-8") as f:
        return f.read()

def write_text(path: str, content: str) -> None:
    """Write text to a file atomically, ensuring newline termination."""
    tmp = path + ".tmp"
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(tmp, "w", encoding="utf-8", newline="\n") as f:
        f.write(content.rstrip() + "\n")
    os.replace(tmp, path)

# -----------------------------------------------------------------------------
# mosquitto.conf parsing (listeners with effective Auth/TLS)

_BOOL_TRUE = {"true", "1", "yes", "on"}

def _to_bool(s: str) -> bool:
    return s.strip().lower() in _BOOL_TRUE

def parse_mosquitto_conf_listeners(path: str = MOSQCONF):
    """
    Parse mosquitto.conf to extract listeners and their effective Auth/TLS config.

    Returns:
        (listeners, meta) where:
          listeners: List[{
              "port": int,
              "address": Optional[str],
              "auth": {
                  "allow_anonymous": Optional[bool],
                  "password_file": Optional[str],
                  "acl_file": Optional[str],
              },
              "tls": {
                  "cafile": Optional[str],
                  "capath": Optional[str],
                  "certfile": Optional[str],
                  "keyfile": Optional[str],
                  "require_certificate": Optional[bool],
                  "use_identity_as_username": Optional[bool],
                  "crlfile": Optional[str],
                  "tls_version": Optional[str],
                  "ciphers": Optional[str],
              },
              "per_listener_settings": bool
          }]
          meta: {
              "per_listener_settings": bool,
              "globals": { "auth": {...}, "tls": {...} }
          }
    """
    text = read_text_or(path, "")
    per_listener = False
    globals_auth: Dict[str, Any] = {}
    globals_tls: Dict[str, Any] = {}

    listeners: List[Dict[str, Any]] = []
    cur: Optional[Dict[str, Any]] = None

    def _apply_auth(target: Dict[str, Any], key: str, args: List[str]):
        if not args:
            return
        if key == "allow_anonymous":
            target["allow_anonymous"] = _to_bool(args[0])
        elif key == "password_file":
            target["password_file"] = " ".join(args)
        elif key == "acl_file":
            target["acl_file"] = " ".join(args)

    def _apply_tls(target: Dict[str, Any], key: str, args: List[str]):
        if not args:
            return
        if key in ("require_certificate", "use_identity_as_username"):
            target[key] = _to_bool(args[0])
        else:
            target[key] = " ".join(args)

    for raw in text.splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        key = parts[0].lower()
        args = parts[1:]

        if key == "per_listener_settings" and args:
            per_listener = _to_bool(args[0])
            continue

        if key == "listener" and args:
            if cur:
                listeners.append(cur)
            port = int(args[0])
            addr = args[1] if len(args) > 1 else None
            cur = {"port": port, "address": addr, "auth": {}, "tls": {}}
            continue

        if key in ("allow_anonymous", "password_file", "acl_file"):
            if per_listener and cur is not None:
                _apply_auth(cur["auth"], key, args)
            else:
                _apply_auth(globals_auth, key, args)
            continue

        if key in (
            "cafile", "capath", "certfile", "keyfile", "require_certificate",
            "use_identity_as_username", "crlfile", "tls_version", "ciphers"
        ):
            if per_listener and cur is not None:
                _apply_tls(cur["tls"], key, args)
            else:
                _apply_tls(globals_tls, key, args)
            continue

    if cur:
        listeners.append(cur)

    # Compose effective settings per listener
    for l in listeners:
        for k, v in globals_auth.items():
            l["auth"].setdefault(k, v)
        for k, v in globals_tls.items():
            l["tls"].setdefault(k, v)
        l["per_listener_settings"] = per_listener

    meta = {
        "per_listener_settings": per_listener,
        "globals": {"auth": globals_auth, "tls": globals_tls},
    }
    return listeners, meta