[server]
port = 8088
address = "0.0.0.0"
enableCORS = false
headless = true
sslCertFile = "/admin-gui/config/admin-ui.crt"
sslKeyFile  = "/admin-gui/config/admin-ui.key"

[client]
toolbarMode = "viewer"

[browser]
gatherUsageStats = false
